import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'pl' | 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pl: {
    // Navigation
    'nav.home': 'Strona główna',
    'nav.gallery': 'Galeria',
    'nav.pricing': 'Cennik',
    'nav.area': 'Okolica',
    'nav.contact': 'Kontakt',
    'nav.booking': 'Rezerwacja',
    
    // Footer
    'footer.contact': 'Kontakt',
    'footer.phone': 'Telefon',
    'footer.email': 'Email',
    'footer.address': 'Adres',
    'footer.links': 'Przydatne linki',
    'footer.privacy': 'Polityka prywatności',
    'footer.terms': 'Regulamin',
    'footer.rights': 'Wszystkie prawa zastrzeżone',
    
    // Homepage
    'hero.title': 'Odkryj spokój w sercu natury',
    'hero.subtitle': 'Nowoczesne domki nad jeziorem w Rogowie - idealne miejsce na wypoczynek z rodziną',
    'hero.cta': 'Zarezerwuj teraz',
    'hero.gallery': 'Zobacz galerię',
    
    // Homepage
    'home.hero.title': 'Lazur Resort',
    'home.hero.subtitle': 'Domki Rogowo',
    'home.hero.description': 'Odkryj spokój i komfort w naszych domkach położonych między Kołobrzegiem a Mrzeżynem. Zaledwie 350 metrów od pięknej, piaszczystej plaży Bałtyku.',
    'home.features.title': 'Dlaczego domki Lazur Resort w Rogowie?',
    'home.features.subtitle': 'Oferujemy komfortowy wypoczynek w domkach nad morzem',
    'home.feature.comfortable.title': 'Komfortowe domki',
    'home.feature.comfortable.desc': 'Domki dla 8 osób z pełnym wyposażeniem',
    'home.feature.sea.title': 'Blisko morza',
    'home.feature.sea.desc': 'Zaledwie 350 metrów do pięknej plaży w Rogowie',
    'home.feature.family.title': 'Dla rodzin',
    'home.feature.family.desc': 'Idealne miejsce na wypoczynek z dziećmi i przyjaciółmi',
    'home.feature.parking.title': 'Bezpłatny parking',
    'home.feature.parking.desc': 'Prywatny parking przy każdym domku',
    'home.feature.wifi.title': 'WiFi i TV',
    'home.feature.wifi.desc': 'Darmowy internet oraz telewizja satelitarna',
    'home.feature.pets.title': 'Akceptujemy zwierzęta',
    'home.feature.pets.desc': 'Twój czworonóg też jest mile widziany',
    'home.cottages.title': 'Nasze domki letniskowe nad morzem',
    'home.cottages.description1': 'Lazur Resort oferuje 4 identyczne domki w Rogowie, każdy zaprojektowany z myślą o maksymalnym komforcie dla 8 osób. Nowoczesne wnętrza łączą elegancję z funkcjonalnością, a przestronne tarasy i prywatne ogrody zapewniają pełną prywatność.',
    'home.cottages.description2': 'Każdy domek wyposażony jest w najwyższej jakości sprzęty i meble. Duże okna wpuszczają dużo naturalnego światła, tworząc przyjazną i ciepłą atmosferę. Idealne miejsce na rodzinne wakacje, wyjazd z przyjaciółmi czy romantyczny weekend nad morzem.',
    'home.cottages.feature1': '2 sypialnie + salon z rozkładaną sofą',
    'home.cottages.feature2': 'W pełni wyposażona kuchnia',
    'home.cottages.feature3': '1 łazienka z prysznicem',
    'home.cottages.feature4': 'Duży taras z meblami ogrodowymi',
    'home.pets.title': 'Pobyt z czworonogiem',
    'home.pets.desc': 'Akceptujemy zwierzęta domowe. Duże tereny zielone i bliskość plaży to idealne warunki dla Twojego pupila.',
    'home.pets.feature1': 'Zwierzęta dozwolone za dopłatą 15 zł/dobę',
    'home.pets.feature2': 'Duży ogród przy każdym domku',
    'home.pets.feature3': 'Blisko plaża przyjazna psom',
    'home.bikes.title': 'Rowerem nad morzem',
    'home.bikes.desc': 'Odkryj urokliwe ścieżki rowerowe łączące Rogowo z Mrzeżynem, Dźwirzynem i Kołobrzegiem.',
    'home.bikes.feature1': 'Trasy dla całej rodziny',
    'home.bikes.feature2': 'Przepiękne widoki na morze',
    'home.bikes.feature3': 'Bezpieczne ścieżki rowerowe',
    'home.location.title': 'Lokalizacja - Rogowo nad morzem',
    'home.location.subtitle': 'Idealnie położone domki między najpopularniejszymi nadmorskimi kurortami',
    'home.location.address': 'Adres',
    'home.location.address.value': 'Makowa 6, 72-330 Rogowo, województwo zachodniopomorskie',
    'home.location.directions': 'Jak do nas dojechać?',
    'home.location.direction1': '15 km od Kołobrzegu',
    'home.location.direction2': '350 metrów do plaży',
    'home.location.direction3': 'Dojazd z Kołobrzegu drogą wojewódzką nr 163',
    'home.location.direction4': 'Następnie skręt w Rogowo zgodnie ze znakowaniem',
    'home.reviews.title': 'Najwyżej oceniane Domki letniskowe 2025',
    'home.reviews.subtitle': 'Zobacz co mówią nasi goście o pobycie w Lazur Resort',
    
    // Contact
    'contact.title': 'Kontakt - Lazur Resort Rogowo',
    'contact.subtitle': 'Skontaktuj się z nami w sprawie rezerwacji domków letniskowych nad morzem w Rogowie. Chętnie odpowiemy na wszystkie pytania dotyczące noclegów dla 8 osób.',
    'contact.info.title': 'Informacje kontaktowe',
    'contact.phone': 'Telefon',
    'contact.phone.hours': 'Czynne codziennie 8:00 - 20:00',
    'contact.email': 'Email',
    'contact.email.response': 'Odpowiadamy w ciągu 24 godzin',
    'contact.address': 'Adres',
    'contact.address.region': 'województwo zachodniopomorskie',
    'contact.hours': 'Godziny kontaktu',
    'contact.hours.value': 'Poniedziałek - Niedziela: 8:00 - 20:00',
    'contact.hours.online': 'Rezerwacje przyjmujemy całą dobę online',
    'contact.directions.title': 'Jak do nas dojechać?',
    'contact.directions.kolobrzeg': '15 km od Kołobrzegu',
    'contact.directions.kolobrzeg.desc': 'Dojazd z Kołobrzegu drogą wojewódzką nr 163 w kierunku Mrzeżyna, następnie skręt w Rogowo zgodnie ze znakowaniem.',
    'contact.directions.beach': '350 metrów do plaży',
    'contact.directions.beach.desc': 'Zaledwie 350 metrów do pięknej plaży w Rogowie - spacer zajmuje około 5 minut.',
    'contact.form.title': 'Wyślij zapytanie o domki letniskowe',
    'contact.form.name': 'Imię',
    'contact.form.surname': 'Nazwisko',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Telefon',
    'contact.form.checkin': 'Data przyjazdu',
    'contact.form.checkout': 'Data wyjazdu',
    'contact.form.guests': 'Liczba osób',
    'contact.form.guests.placeholder': '8 osób',
    'contact.form.message': 'Wiadomość',
    'contact.form.message.placeholder': 'Dodatkowe informacje, pytania o domki letniskowe nad morzem...',
    'contact.form.submit': 'Wyślij zapytanie o rezerwację',
    'contact.form.required': 'Pola wymagane. Odpowiemy w ciągu 24 godzin.',
    'contact.why.title': 'Dlaczego warto wybrać domki Lazur Resort w Rogowie?',
    'contact.why.sea': 'Blisko morza',
    'contact.why.sea.desc': 'Zaledwie 350 metrów do pięknej plaży w Rogowie',
    'contact.why.location': 'Doskonała lokalizacja',
    'contact.why.location.desc': 'Blisko Kołobrzegu, Mrzeżyna i innych atrakcji turystycznych',
    'contact.why.service': 'Profesjonalna obsługa',
    'contact.why.service.desc': 'Zawsze chętnie pomożemy i odpowiemy na pytania',
    
    // Reservation
    'reservation.title': 'Rezerwacja Domków Letniskowych Lazur Resort',
    'reservation.subtitle': 'Zarezerwuj swój domek nad morzem w Rogowie już dziś! Domki z 2 sypialniami dla 8 osób w województwie zachodniopomorskim z pełnym komfortem.',
    'reservation.form.title': 'Formularz rezerwacji domku',
    'reservation.form.firstname': 'Imię',
    'reservation.form.lastname': 'Nazwisko',
    'reservation.form.email': 'Email',
    'reservation.form.phone': 'Telefon',
    'reservation.form.checkin': 'Data przyjazdu',
    'reservation.form.checkout': 'Data wyjazdu',
    'reservation.form.guests': 'Liczba osób',
    'reservation.form.children': 'Liczba dzieci',
    'reservation.form.pet': 'Czy przyjeżdżacie z psem?',
    'reservation.form.pet.no': 'Nie',
    'reservation.form.pet.yes': 'Tak (+15 zł/dobę)',
    'reservation.form.additional': 'Dodatkowe informacje',
    'reservation.form.additional.placeholder': 'Szczególne życzenia, pytania o domek letniskowy nad morzem...',
    'reservation.form.info.title': 'Informacja o rezerwacji:',
    'reservation.form.info.desc': 'Po wysłaniu formularza skontaktujemy się z Państwem w ciągu 24 godzin w celu potwierdzenia dostępności i warunków rezerwacji domku letniskowego.',
    'reservation.form.submit': 'Wyślij zapytanie o rezerwację',
    'reservation.cottage.title': 'Domki Lazur Resort',
    'reservation.cottage.available': 'Dostępne domki:',
    'reservation.cottage.type': 'Typ domku:',
    'reservation.cottage.type.value': '2 sypialnie + salon',
    'reservation.cottage.prices': 'Ceny dla domku (8 osób):',
    'reservation.cottage.price.4': 'Do 4 osób:',
    'reservation.cottage.price.4.value': '400-650 zł/noc',
    'reservation.cottage.price.6': '5-6 osób:',
    'reservation.cottage.price.6.value': '450-700 zł/noc',
    'reservation.cottage.price.8': '7-8 osób:',
    'reservation.cottage.price.8.value': '500-750 zł/noc',
    'reservation.cottage.distance': 'Odległość do morza: 350 metrów',
    'reservation.cottage.parking': 'Parking: bezpłatny przy każdym domku',
    'reservation.contact.title': 'Kontakt bezpośredni',
    'reservation.contact.phone.hours': 'Czynne codziennie 8:00 - 20:00',
    'reservation.contact.email.response': 'Odpowiadamy w ciągu 24 godzin',
    'reservation.contact.desc': 'Preferujesz kontakt telefoniczny? Zadzwoń do nas bezpośrednio, zawsze jesteśmy do Państwa dyspozycji.',
    'reservation.why.title': 'Dlaczego rezerwować domki w Lazur Resort Rogowo?',
    'reservation.why.price': 'Gwarancja najlepszej ceny',
    'reservation.why.price.desc': 'Konkurencyjne ceny noclegów nad morzem',
    'reservation.why.service': 'Obsługa 24/7',
    'reservation.why.service.desc': 'Zawsze jesteśmy do Państwa dyspozycji',
    
    // Gallery
    'gallery.title': 'Galeria Domków Lazur Resort',
    'gallery.subtitle': 'Zobacz nasze domki letniskowe nad morzem w Rogowie. Komfortowe wnętrza i piękne otoczenie czekają na Państwa.',
    'gallery.exterior': 'Widoki zewnętrzne',
    'gallery.interior': 'Wnętrza domków',
    'gallery.comfort.title': 'Każdy domek oferuje pełen komfort',
    'gallery.space.title': 'Przestrzeń mieszkalna',
    'gallery.space.bedrooms': '2 sypialnie dla 8 osób',
    'gallery.space.living': 'Salon z rozkładaną sofą',
    'gallery.space.kitchen': 'Kuchnia z pełnym wyposażeniem',
    'gallery.space.bathroom': 'Łazienka z prysznicem',
    'gallery.relax.title': 'Strefa relaksu',
    'gallery.relax.terrace': 'Duży taras z meblami',
    'gallery.relax.garden': 'Prywatny ogród',
    'gallery.relax.grill': 'Miejsce na grilla',
    'gallery.relax.parking': 'Parking przy domku',
    'gallery.amenities.title': 'Udogodnienia',
    'gallery.amenities.wifi': 'WiFi i telewizja',
    'gallery.amenities.linen': 'Pościel i ręczniki',
    'gallery.amenities.pets': 'Miejsce dla zwierząt',
    'gallery.amenities.beach': '350m do plaży',
    
    // Pricing
    'pricing.title': 'Cennik domków letniskowych',
    'pricing.subtitle': 'Sprawdź nasze konkurencyjne ceny na pobyt w domkach nad morzem w Rogowie',
    'pricing.season.spring': 'Sezon wiosenny',
    'pricing.season.spring.desc': 'Idealne na spokojny wypoczynek wiosną',
    'pricing.season.mayday': 'Majówka',
    'pricing.season.mayday.desc': 'Długi weekend majowy',
    'pricing.season.prevacation': 'Sezon przedwakacyjny',
    'pricing.season.prevacation.desc': 'Doskonały czas przed sezonem letnim',
    'pricing.season.summstart': 'Początek lata',
    'pricing.season.summstart.desc': 'Rozpoczęcie sezonu letniego',
    'pricing.season.high': 'Sezon wysoki',
    'pricing.season.high.desc': 'Najlepszy czas na wakacje z rodziną',
    'pricing.season.summend': 'Koniec lata',
    'pricing.season.summend.desc': 'Spokojniejszy koniec wakacji',
    'pricing.season.autumn': 'Sezon jesienny',
    'pricing.season.autumn.desc': 'Złota polska jesień nad morzem',
    'pricing.cottage.4': 'Domek 4 osobowy:',
    'pricing.cottage.56': 'Domek 5-6 osobowy:',
    'pricing.cottage.78': 'Domek 7-8 osobowy:',
    'pricing.per.night': 'zł/noc',
    'pricing.includes.title': 'Co zawiera cena domku letniskowego?',
    'pricing.includes.accommodation': 'Nocleg dla maksymalnie 4, 6 lub 8 osób',
    'pricing.includes.bedrooms': '2 sypialnie + salon z rozkładaną sofą',
    'pricing.includes.kitchen': 'W pełni wyposażona kuchnia',
    'pricing.includes.bathroom': '1 łazienka z prysznicem',
    'pricing.includes.terrace': 'Duży taras z meblami ogrodowymi',
    'pricing.includes.wifi': 'WiFi i telewizja satelitarna',
    'pricing.includes.grill': 'Miejsce na grilla',
    'pricing.includes.parking': 'Bezpłatny parking',
    'pricing.includes.linen': 'Pościel i ręczniki',
    'pricing.includes.beach': '5 minut pieszo do morza',
    'pricing.terms.title': 'Warunki rezerwacji',
    'pricing.terms.minimum': 'Minimalna rezerwacja: 2 noce',
    'pricing.terms.checkin': 'Zameldowanie: od 15:00',
    'pricing.terms.checkout': 'Wymeldowanie: do 10:00',
    'pricing.terms.deposit': 'Zadatek: 20% wartości pobytu',
    'pricing.terms.pets': 'Zwierzęta: dozwolone za dopłatą 15 zł/dobę',
    'pricing.terms.distance': 'Odległość do morza: 350 metrów',
    'pricing.terms.parking': 'Parking: bezpłatny przy każdym domku',
    'pricing.additional.title': 'Informacje dodatkowe',
    'pricing.additional.desc': 'Domek dla 8 osób: 2 sypialnie + salon z rozkładanymi sofami i łóżkiem narożnym',
    'pricing.cta.title': 'Gotowy na niezapomniany pobyt?',
    'pricing.cta.subtitle': 'Zarezerwuj swój domek nad morzem już dziś i ciesz się komfortowym wypoczynkiem w Rogowie',
    'pricing.cta.button': 'Sprawdź dostępność',
    
    // Area
    'area.title': 'Odkryj Okolicę',
    'area.subtitle': 'Rogowo to idealna baza wypadowa do odkrywania pięknych miejscowości nadmorskich. Poznaj uroki pobliskich miasteczek i atrakcji regionu.',
    'area.mrzezyna.title': 'Domki na wynajem Mrzeżyno',
    'area.mrzezyna.desc': 'Spokojne miasteczko nad morzem z piękną plażą i urokliwym portem rybackim.',
    'area.dzwirzyno.title': 'Domki na wynajem Dźwirzyno',
    'area.dzwirzyno.desc': 'Malownicza miejscowość między morzem a jeziorem Resko Przymorskie.',
    'area.kolobrzeg.title': 'Domki na wynajem Kołobrzeg',
    'area.kolobrzeg.desc': 'Znany kurort nadmorski z licznymi atrakcjami i zabytkami.',
    'area.pets.title': 'Noclegi z psem',
    'area.pets.desc': 'Idealne miejsca dla właścicieli psów z przyjaznymi regulacjami.',
    'area.bikes.title': 'Ścieżki rowerowe',
    'area.bikes.desc': 'Malownicze trasy rowerowe wzdłuż wybrzeża i przez lasy.',
    'area.why.title': 'Dlaczego warto wybrać Rogowo?',
    'area.why.location': 'Centralna Lokalizacja',
    'area.why.location.desc': 'Idealne położenie między Kołobrzegiem, Mrzeżynem i Dźwirzynem',
    'area.why.beach': 'Bliskość Plaży',
    'area.why.beach.desc': 'Zaledwie kilka minut jazdy do pięknych plaż Bałtyku',
    'area.why.nature': 'Spokój i Natura',
    'area.why.nature.desc': 'Otoczone lasami i zielenią, z dala od miejskiego zgiełku',

    // Common
    'button.book': 'Rezerwacja',
    'button.contact': 'Skontaktuj się',
    'button.more': 'Dowiedz się więcej',
    'button.back': 'Powrót',
    'button.gallery': 'Zobacz galerię',
    'required': '*',
  },
  
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.gallery': 'Galerie',
    'nav.pricing': 'Preise',
    'nav.area': 'Umgebung',
    'nav.contact': 'Kontakt',
    'nav.booking': 'Buchung',
    
    // Footer
    'footer.contact': 'Kontakt',
    'footer.phone': 'Telefon',
    'footer.email': 'E-Mail',
    'footer.address': 'Adresse',
    'footer.links': 'Nützliche Links',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'AGB',
    'footer.rights': 'Alle Rechte vorbehalten',
    
    // Homepage
    'hero.title': 'Entdecken Sie Ruhe im Herzen der Natur',
    'hero.subtitle': 'Moderne Häuschen am See in Rogowo - der perfekte Ort für einen Familienurlaub',
    'hero.cta': 'Jetzt buchen',
    'hero.gallery': 'Galerie ansehen',
    
    // Homepage
    'home.hero.title': 'Lazur Resort',
    'home.hero.subtitle': 'Ferienhäuser am Meer in Rogowo',
    'home.hero.description': 'Entdecken Sie Ruhe und Komfort in unseren Häusern zwischen Kołobrzeg und Mrzeżyn. Nur 350 Meter vom schönen Sandstrand der Ostsee entfernt.',
    'home.features.title': 'Warum Lazur Resort Häuser in Rogowo?',
    'home.features.subtitle': 'Wir bieten komfortablen Urlaub in Häusern am Meer',
    'home.feature.comfortable.title': 'Komfortable Häuser',
    'home.feature.comfortable.desc': 'Häuser für 8 Personen mit vollständiger Ausstattung',
    'home.feature.sea.title': 'Nahe am Meer',
    'home.feature.sea.desc': 'Nur 400 Meter zum schönen Strand in Rogowo',
    'home.feature.family.title': 'Für Familien',
    'home.feature.family.desc': 'Perfekter Ort für Urlaub mit Kindern und Freunden',
    'home.feature.parking.title': 'Kostenloser Parkplatz',
    'home.feature.parking.desc': 'Privater Parkplatz bei jedem Haus',
    'home.feature.wifi.title': 'WiFi und TV',
    'home.feature.wifi.desc': 'Kostenloses Internet und Satellitenfernsehen',
    'home.feature.pets.title': 'Haustiere willkommen',
    'home.feature.pets.desc': 'Ihr Vierbeiner ist auch herzlich willkommen',
    'home.cottages.title': 'Unsere Ferienhäuser am Meer',
    'home.cottages.description1': 'Lazur Resort bietet 4 identische Häuser in Rogowo, jedes für Komfort für 8 Personen konzipiert. Moderne Innenräume verbinden Eleganz mit Funktionalität, und geräumige Terrassen und private Gärten gewährleisten absolute Privatsphäre.',
    'home.cottages.description2': 'Jedes Haus ist mit hochwertigen Geräten und Möbeln ausgestattet. Große Fenster lassen viel natürliches Licht herein und schaffen eine freundliche und warme Atmosphäre. Perfekter Ort für Familienurlaub, Ausflug mit Freunden oder romantisches Wochenende am Meer.',
    'home.cottages.feature1': '2 Schlafzimmer + Wohnzimmer mit Schlafsofa',
    'home.cottages.feature2': 'Voll ausgestattete Küche',
    'home.cottages.feature3': '1 Badezimmer mit Dusche',
    'home.cottages.feature4': 'Große Terrasse mit Gartenmöbeln',
    'home.pets.title': 'Aufenthalt mit Vierbeiner',
    'home.pets.desc': 'Wir akzeptieren Haustiere. Große Grünflächen und die Nähe zum Strand sind ideale Bedingungen für Ihren Liebling.',
    'home.pets.feature1': 'Tiere erlaubt gegen Aufpreis 15 zł/Tag',
    'home.pets.feature2': 'Großer Garten bei jedem Haus',
    'home.pets.feature3': 'Hundefreundlicher Strand in der Nähe',
    'home.bikes.title': 'Mit dem Fahrrad am Meer',
    'home.bikes.desc': 'Entdecken Sie reizvolle Radwege, die Rogowo mit Mrzeżyn, Dźwirzyno und Kołobrzeg verbinden.',
    'home.bikes.feature1': 'Routen für die ganze Familie',
    'home.bikes.feature2': 'Wunderschöne Meerblicke',
    'home.bikes.feature3': 'Sichere Radwege',
    'home.location.title': 'Lage - Rogowo am Meer',
    'home.location.subtitle': 'Ideal gelegene Häuser zwischen den beliebtesten Badeorten',
    'home.location.address': 'Adresse',
    'home.location.address.value': 'Makowa 6, 72-330 Rogowo, Westpommern',
    'home.location.directions': 'Wie erreichen Sie uns?',
    'home.location.direction1': '15 km von Kołobrzeg',
    'home.location.direction2': '350 Meter zum Strand',
    'home.location.direction3': 'Anfahrt von Kołobrzeg über Landesstraße Nr. 163',
    'home.location.direction4': 'Dann Abzweigung in Rogowo entsprechend Beschilderung',
    'home.reviews.title': 'Bestbewertete Ferienhäuser 2025',
    'home.reviews.subtitle': 'Sehen Sie was unsere Gäste über den Aufenthalt im Lazur Resort sagen',
    
    // Contact
    'contact.title': 'Kontakt - Lazur Resort Rogowo',
    'contact.subtitle': 'Kontaktieren Sie uns bezüglich der Reservierung von Ferienhäusern am Meer in Rogowo. Gerne beantworten wir alle Fragen zu Unterkünften für 8 Personen.',
    'contact.info.title': 'Kontaktinformationen',
    'contact.phone': 'Telefon',
    'contact.phone.hours': 'Täglich geöffnet 8:00 - 20:00',
    'contact.email': 'E-Mail',
    'contact.email.response': 'Antwort innerhalb von 24 Stunden',
    'contact.address': 'Adresse',
    'contact.address.region': 'Westpommern',
    'contact.hours': 'Kontaktzeiten',
    'contact.hours.value': 'Montag - Sonntag: 8:00 - 20:00',
    'contact.hours.online': 'Reservierungen nehmen wir rund um die Uhr online entgegen',
    'contact.directions.title': 'Wie erreichen Sie uns?',
    'contact.directions.kolobrzeg': '15 km von Kołobrzeg',
    'contact.directions.kolobrzeg.desc': 'Anfahrt von Kołobrzeg über Landesstraße Nr. 163 Richtung Mrzeżyn, dann Abzweigung in Rogowo entsprechend Beschilderung.',
    'contact.directions.beach': '350 Meter zum Strand',
    'contact.directions.beach.desc': 'Nur 350 Meter zum schönen Strand in Rogowo - der Spaziergang dauert etwa 5 Minuten.',
    'contact.form.title': 'Anfrage für Ferienhäuser senden',
    'contact.form.name': 'Vorname',
    'contact.form.surname': 'Nachname',
    'contact.form.email': 'E-Mail',
    'contact.form.phone': 'Telefon',
    'contact.form.checkin': 'Anreisedatum',
    'contact.form.checkout': 'Abreisedatum',
    'contact.form.guests': 'Anzahl der Personen',
    'contact.form.guests.placeholder': '8 Personen',
    'contact.form.message': 'Nachricht',
    'contact.form.message.placeholder': 'Zusätzliche Informationen, Fragen zu Ferienhäusern am Meer...',
    'contact.form.submit': 'Reservierungsanfrage senden',
    'contact.form.required': 'Pflichtfelder. Antwort innerhalb von 24 Stunden.',
    'contact.why.title': 'Warum Lazur Resort Häuser in Rogowo wählen?',
    'contact.why.sea': 'Nahe am Meer',
    'contact.why.sea.desc': 'Nur 400 Meter zum schönen Strand in Rogowo',
    'contact.why.location': 'Ausgezeichnete Lage',
    'contact.why.location.desc': 'Nahe Kołobrzeg, Mrzeżyn und anderen Touristenattraktionen',
    'contact.why.service': 'Professioneller Service',
    'contact.why.service.desc': 'Wir helfen immer gerne und beantworten Fragen',
    
    // Reservation
    'reservation.title': 'Reservierung Ferienhäuser Lazur Resort',
    'reservation.subtitle': 'Reservieren Sie Ihr Haus am Meer in Rogowo noch heute! Häuser mit 2 Schlafzimmern für 8 Personen in Westpommern mit vollem Komfort.',
    'reservation.form.title': 'Hausreservierungsformular',
    'reservation.form.firstname': 'Vorname',
    'reservation.form.lastname': 'Nachname',
    'reservation.form.email': 'E-Mail',
    'reservation.form.phone': 'Telefon',
    'reservation.form.checkin': 'Anreisedatum',
    'reservation.form.checkout': 'Abreisedatum',
    'reservation.form.guests': 'Anzahl der Personen',
    'reservation.form.children': 'Anzahl der Kinder',
    'reservation.form.pet': 'Reisen Sie mit einem Hund?',
    'reservation.form.pet.no': 'Nein',
    'reservation.form.pet.yes': 'Ja (+15 zł/Tag)',
    'reservation.form.additional': 'Zusätzliche Informationen',
    'reservation.form.additional.placeholder': 'Besondere Wünsche, Fragen zum Ferienhaus am Meer...',
    'reservation.form.info.title': 'Reservierungsinformation:',
    'reservation.form.info.desc': 'Nach dem Senden des Formulars kontaktieren wir Sie innerhalb von 24 Stunden zur Bestätigung der Verfügbarkeit und Bedingungen der Hausreservierung.',
    'reservation.form.submit': 'Reservierungsanfrage senden',
    'reservation.cottage.title': 'Lazur Resort Häuser',
    'reservation.cottage.available': 'Verfügbare Häuser:',
    'reservation.cottage.type': 'Haustyp:',
    'reservation.cottage.type.value': '2 Schlafzimmer + Wohnzimmer',
    'reservation.cottage.prices': 'Preise für Haus (8 Personen):',
    'reservation.cottage.price.4': 'Bis 4 Personen:',
    'reservation.cottage.price.4.value': '400-650 zł/Nacht',
    'reservation.cottage.price.6': '5-6 Personen:',
    'reservation.cottage.price.6.value': '450-700 zł/Nacht',
    'reservation.cottage.price.8': '7-8 Personen:',
    'reservation.cottage.price.8.value': '500-750 zł/Nacht',
    'reservation.cottage.distance': 'Entfernung zum Meer: 350 Meter',
    'reservation.cottage.parking': 'Parkplatz: kostenlos bei jedem Haus',
    'reservation.contact.title': 'Direkter Kontakt',
    'reservation.contact.phone.hours': 'Täglich geöffnet 8:00 - 20:00',
    'reservation.contact.email.response': 'Antwort innerhalb von 24 Stunden',
    'reservation.contact.desc': 'Bevorzugen Sie telefonischen Kontakt? Rufen Sie uns direkt an, wir stehen Ihnen immer zur Verfügung.',
    'reservation.why.title': 'Warum Häuser im Lazur Resort Rogowo reservieren?',
    'reservation.why.price': 'Bestpreisgarantie',
    'reservation.why.price.desc': 'Wettbewerbsfähige Preise für Übernachtungen am Meer',
    'reservation.why.service': '24/7 Service',
    'reservation.why.service.desc': 'Wir stehen Ihnen immer zur Verfügung',
    
    // Gallery
    'gallery.title': 'Galerie Lazur Resort Häuser',
    'gallery.subtitle': 'Sehen Sie unsere Ferienhäuser am Meer in Rogowo. Komfortable Innenräume und schöne Umgebung warten auf Sie.',
    'gallery.exterior': 'Außenansichten',
    'gallery.interior': 'Hausinneres',
    'gallery.comfort.title': 'Jedes Haus bietet vollen Komfort',
    'gallery.space.title': 'Wohnraum',
    'gallery.space.bedrooms': '2 Schlafzimmer für 8 Personen',
    'gallery.space.living': 'Wohnzimmer mit Schlafsofa',
    'gallery.space.kitchen': 'Voll ausgestattete Küche',
    'gallery.space.bathroom': 'Badezimmer mit Dusche',
    'gallery.relax.title': 'Entspannungsbereich',
    'gallery.relax.terrace': 'Große Terrasse mit Möbeln',
    'gallery.relax.garden': 'Privater Garten',
    'gallery.relax.grill': 'Grillplatz',
    'gallery.relax.parking': 'Parkplatz am Haus',
    'gallery.amenities.title': 'Annehmlichkeiten',
    'gallery.amenities.wifi': 'WiFi und Fernsehen',
    'gallery.amenities.linen': 'Bettwäsche und Handtücher',
    'gallery.amenities.pets': 'Platz für Tiere',
    'gallery.amenities.beach': '350m zum Strand',
    
    // Pricing
    'pricing.title': 'Preisliste Ferienhäuser',
    'pricing.subtitle': 'Schauen Sie sich unsere wettbewerbsfähigen Preise für einen Aufenthalt in Häusern am Meer in Rogowo an',
    'pricing.season.spring': 'Frühlingssaison',
    'pricing.season.spring.desc': 'Ideal für ruhige Entspannung im Frühling',
    'pricing.season.mayday': 'Maifeiertag',
    'pricing.season.mayday.desc': 'Langes Mai-Wochenende',
    'pricing.season.prevacation': 'Vor-Urlaubssaison',
    'pricing.season.prevacation.desc': 'Ausgezeichnete Zeit vor der Sommersaison',
    'pricing.season.summstart': 'Sommerbeginn',
    'pricing.season.summstart.desc': 'Beginn der Sommersaison',
    'pricing.season.high': 'Hochsaison',
    'pricing.season.high.desc': 'Beste Zeit für Familienurlaub',
    'pricing.season.summend': 'Sommerende',
    'pricing.season.summend.desc': 'Ruhigeres Urlaubsende',
    'pricing.season.autumn': 'Herbstsaison',
    'pricing.season.autumn.desc': 'Goldener polnischer Herbst am Meer',
    'pricing.cottage.4': 'Haus für 4 Personen:',
    'pricing.cottage.56': 'Haus für 5-6 Personen:',
    'pricing.cottage.78': 'Haus für 7-8 Personen:',
    'pricing.per.night': 'zł/Nacht',
    'pricing.includes.title': 'Was ist im Preis des Ferienhauses enthalten?',
    'pricing.includes.accommodation': 'Übernachtung für maximal 4, 6 oder 8 Personen',
    'pricing.includes.bedrooms': '2 Schlafzimmer + Wohnzimmer mit Schlafsofa',
    'pricing.includes.kitchen': 'Voll ausgestattete Küche',
    'pricing.includes.bathroom': '1 Badezimmer mit Dusche',
    'pricing.includes.terrace': 'Große Terrasse mit Gartenmöbeln',
    'pricing.includes.wifi': 'WiFi und Satellitenfernsehen',
    'pricing.includes.grill': 'Grillplatz',
    'pricing.includes.parking': 'Kostenloser Parkplatz',
    'pricing.includes.linen': 'Bettwäsche und Handtücher',
    'pricing.includes.beach': '5 Minuten zu Fuß zum Meer',
    'pricing.terms.title': 'Reservierungsbedingungen',
    'pricing.terms.minimum': 'Mindestbuchung: 2 Nächte',
    'pricing.terms.checkin': 'Check-in: ab 15:00',
    'pricing.terms.checkout': 'Check-out: bis 10:00',
    'pricing.terms.deposit': 'Anzahlung: 20% des Aufenthaltswertes',
    'pricing.terms.pets': 'Tiere: erlaubt gegen Aufpreis 15 zł/Tag',
    'pricing.terms.distance': 'Entfernung zum Meer: 350 Meter',
    'pricing.terms.parking': 'Parkplatz: kostenlos bei jedem Haus',
    'pricing.additional.title': 'Zusätzliche Informationen',
    'pricing.additional.desc': 'Haus für 8 Personen: 2 Schlafzimmer + Wohnzimmer mit ausklappbaren Sofas und Eckbett',
    'pricing.cta.title': 'Bereit für einen unvergesslichen Aufenthalt?',
    'pricing.cta.subtitle': 'Reservieren Sie Ihr Haus am Meer noch heute und genießen Sie einen komfortablen Urlaub in Rogowo',
    'pricing.cta.button': 'Verfügbarkeit prüfen',
    
    // Area
    'area.title': 'Entdecken Sie die Umgebung',
    'area.subtitle': 'Rogowo ist ein idealer Ausgangspunkt zur Erkundung schöner Küstenorte. Lernen Sie die Reize der nahegelegenen Städte und Attraktionen der Region kennen.',
    'area.mrzezyna.title': 'Häuser zu vermieten Mrzeżyn',
    'area.mrzezyna.desc': 'Ruhige Küstenstadt mit schönem Strand und charmantem Fischerhafen.',
    'area.dzwirzyno.title': 'Häuser zu vermieten Dźwirzyno',
    'area.dzwirzyno.desc': 'Malerischer Ort zwischen Meer und Resko Przymorskie See.',
    'area.kolobrzeg.title': 'Häuser zu vermieten Kołobrzeg',
    'area.kolobrzeg.desc': 'Bekannter Küstenort mit zahlreichen Attraktionen und Denkmälern.',
    'area.pets.title': 'Unterkunft mit Hund',
    'area.pets.desc': 'Ideale Orte für Hundebesitzer mit haustierfreundlichen Regelungen.',
    'area.bikes.title': 'Radwege',
    'area.bikes.desc': 'Malerische Radrouten entlang der Küste und durch Wälder.',
    'area.why.title': 'Warum Rogowo wählen?',
    'area.why.location': 'Zentrale Lage',
    'area.why.location.desc': 'Ideale Lage zwischen Kołobrzeg, Mrzeżyn und Dźwirzyno',
    'area.why.beach': 'Strandnähe',
    'area.why.beach.desc': 'Nur wenige Minuten Fahrt zu den schönen Stränden der Ostsee',
    'area.why.nature': 'Ruhe und Natur',
    'area.why.nature.desc': 'Umgeben von Wäldern und Grün, fernab vom Stadtlärm',

    // Common
    'button.book': 'Reservierung',
    'button.contact': 'Kontaktieren',
    'button.more': 'Mehr erfahren',
    'button.back': 'Zurück',
    'button.gallery': 'Galerie ansehen',
    'required': '*',
  },
  
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.gallery': 'Gallery',
    'nav.pricing': 'Pricing',
    'nav.area': 'Area',
    'nav.contact': 'Contact',
    'nav.booking': 'Booking',
    
    // Footer
    'footer.contact': 'Contact',
    'footer.phone': 'Phone',
    'footer.email': 'Email',
    'footer.address': 'Address',
    'footer.links': 'Useful Links',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved',
    
    // Homepage
    'hero.title': 'Discover peace in the heart of nature',
    'hero.subtitle': 'Modern cottages by the lake in Rogowo - perfect place for family vacation',
    'hero.cta': 'Book now',
    'hero.gallery': 'View gallery',
    
    // Homepage
    'home.hero.title': 'Lazur Resort',
    'home.hero.subtitle': 'Holiday cottages by the sea in Rogowo',
    'home.hero.description': 'Discover peace and comfort in our cottages located between Kołobrzeg and Mrzeżyn. Just 350 meters from the beautiful sandy beach of the Baltic Sea.',
    'home.features.title': 'Why Lazur Resort cottages in Rogowo?',
    'home.features.subtitle': 'We offer comfortable vacation in cottages by the sea',
    'home.feature.comfortable.title': 'Comfortable cottages',
    'home.feature.comfortable.desc': 'Cottages for 8 people with full equipment',
    'home.feature.sea.title': 'Close to the sea',
    'home.feature.sea.desc': 'Only 400 meters to the beautiful beach in Rogowo',
    'home.feature.family.title': 'For families',
    'home.feature.family.desc': 'Perfect place for vacation with children and friends',
    'home.feature.parking.title': 'Free parking',
    'home.feature.parking.desc': 'Private parking at each cottage',
    'home.feature.wifi.title': 'WiFi and TV',
    'home.feature.wifi.desc': 'Free internet and satellite television',
    'home.feature.pets.title': 'Pet friendly',
    'home.feature.pets.desc': 'Your four-legged friend is also welcome',
    'home.cottages.title': 'Our holiday cottages by the sea',
    'home.cottages.description1': 'Lazur Resort offers 4 identical cottages in Rogowo, each designed for comfort for 8 people. Modern interiors combine elegance with functionality, and spacious terraces and private gardens ensure complete privacy.',
    'home.cottages.description2': 'Each cottage is equipped with the highest quality appliances and furniture. Large windows let in lots of natural light, creating a friendly and warm atmosphere. Perfect place for family vacation, trip with friends or romantic weekend by the sea.',
    'home.cottages.feature1': '2 bedrooms + living room with sofa bed',
    'home.cottages.feature2': 'Fully equipped kitchen',
    'home.cottages.feature3': '1 bathroom with shower',
    'home.cottages.feature4': 'Large terrace with garden furniture',
    'home.pets.title': 'Stay with your pet',
    'home.pets.desc': 'We accept pets. Large green areas and proximity to the beach are ideal conditions for your pet.',
    'home.pets.feature1': 'Animals allowed for additional fee 15 zł/day',
    'home.pets.feature2': 'Large garden at each cottage',
    'home.pets.feature3': 'Dog-friendly beach nearby',
    'home.bikes.title': 'Cycling by the sea',
    'home.bikes.desc': 'Discover charming bike paths connecting Rogowo with Mrzeżyn, Dźwirzyno and Kołobrzeg.',
    'home.bikes.feature1': 'Routes for the whole family',
    'home.bikes.feature2': 'Beautiful sea views',
    'home.bikes.feature3': 'Safe bike paths',
    'home.location.title': 'Location - Rogowo by the sea',
    'home.location.subtitle': 'Ideally located cottages between the most popular seaside resorts',
    'home.location.address': 'Address',
    'home.location.address.value': 'Makowa 6, 72-330 Rogowo, West Pomeranian Voivodeship',
    'home.location.directions': 'How to reach us?',
    'home.location.direction1': '15 km from Kołobrzeg',
    'home.location.direction2': '350 meters to the beach',
    'home.location.direction3': 'Drive from Kołobrzeg via provincial road No. 163',
    'home.location.direction4': 'Then turn in Rogowo according to signs',
    'home.reviews.title': 'Highest Rated Holiday Cottages 2025',
    'home.reviews.subtitle': 'See what our guests say about staying at Lazur Resort',
    
    // Contact
    'contact.title': 'Contact - Lazur Resort Rogowo',
    'contact.subtitle': 'Contact us regarding holiday cottage reservations by the sea in Rogowo. We are happy to answer all questions about accommodation for 8 people.',
    'contact.info.title': 'Contact information',
    'contact.phone': 'Phone',
    'contact.phone.hours': 'Open daily 8:00 - 20:00',
    'contact.email': 'Email',
    'contact.email.response': 'We respond within 24 hours',
    'contact.address': 'Address',
    'contact.address.region': 'West Pomeranian Voivodeship',
    'contact.hours': 'Contact hours',
    'contact.hours.value': 'Monday - Sunday: 8:00 - 20:00',
    'contact.hours.online': 'We accept reservations 24/7 online',
    'contact.directions.title': 'How to reach us?',
    'contact.directions.kolobrzeg': '15 km from Kołobrzeg',
    'contact.directions.kolobrzeg.desc': 'Drive from Kołobrzeg via provincial road No. 163 towards Mrzeżyn, then turn in Rogowo according to signs.',
    'contact.directions.beach': '350 meters to the beach',
    'contact.directions.beach.desc': 'Only 350 meters to the beautiful beach in Rogowo - the walk takes about 5 minutes.',
    'contact.form.title': 'Send inquiry about holiday cottages',
    'contact.form.name': 'First name',
    'contact.form.surname': 'Last name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.checkin': 'Check-in date',
    'contact.form.checkout': 'Check-out date',
    'contact.form.guests': 'Number of guests',
    'contact.form.guests.placeholder': '8 people',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Additional information, questions about holiday cottages by the sea...',
    'contact.form.submit': 'Send reservation inquiry',
    'contact.form.required': 'Required fields. We respond within 24 hours.',
    'contact.why.title': 'Why choose Lazur Resort cottages in Rogowo?',
    'contact.why.sea': 'Close to the sea',
    'contact.why.sea.desc': 'Only 400 meters to the beautiful beach in Rogowo',
    'contact.why.location': 'Excellent location',
    'contact.why.location.desc': 'Close to Kołobrzeg, Mrzeżyn and other tourist attractions',
    'contact.why.service': 'Professional service',
    'contact.why.service.desc': 'We are always happy to help and answer questions',
    
    // Reservation
    'reservation.title': 'Holiday Cottages Reservation Lazur Resort',
    'reservation.subtitle': 'Reserve your cottage by the sea in Rogowo today! Cottages with 2 bedrooms for 8 people in West Pomeranian Voivodeship with full comfort.',
    'reservation.form.title': 'Cottage reservation form',
    'reservation.form.firstname': 'First name',
    'reservation.form.lastname': 'Last name',
    'reservation.form.email': 'Email',
    'reservation.form.phone': 'Phone',
    'reservation.form.checkin': 'Check-in date',
    'reservation.form.checkout': 'Check-out date',
    'reservation.form.guests': 'Number of guests',
    'reservation.form.children': 'Number of children',
    'reservation.form.pet': 'Are you traveling with a dog?',
    'reservation.form.pet.no': 'No',
    'reservation.form.pet.yes': 'Yes (+15 zł/day)',
    'reservation.form.additional': 'Additional information',
    'reservation.form.additional.placeholder': 'Special requests, questions about holiday cottage by the sea...',
    'reservation.form.info.title': 'Reservation information:',
    'reservation.form.info.desc': 'After sending the form, we will contact you within 24 hours to confirm availability and cottage reservation conditions.',
    'reservation.form.submit': 'Send reservation inquiry',
    'reservation.cottage.title': 'Lazur Resort Cottages',
    'reservation.cottage.available': 'Available cottages:',
    'reservation.cottage.type': 'Cottage type:',
    'reservation.cottage.type.value': '2 bedrooms + living room',
    'reservation.cottage.prices': 'Prices for cottage (8 people):',
    'reservation.cottage.price.4': 'Up to 4 people:',
    'reservation.cottage.price.4.value': '400-650 zł/night',
    'reservation.cottage.price.6': '5-6 people:',
    'reservation.cottage.price.6.value': '450-700 zł/night',
    'reservation.cottage.price.8': '7-8 people:',
    'reservation.cottage.price.8.value': '500-750 zł/night',
    'reservation.cottage.distance': 'Distance to sea: 350 meters',
    'reservation.cottage.parking': 'Parking: free at each cottage',
    'reservation.contact.title': 'Direct contact',
    'reservation.contact.phone.hours': 'Open daily 8:00 - 20:00',
    'reservation.contact.email.response': 'We respond within 24 hours',
    'reservation.contact.desc': 'Prefer phone contact? Call us directly, we are always at your disposal.',
    'reservation.why.title': 'Why reserve cottages at Lazur Resort Rogowo?',
    'reservation.why.price': 'Best price guarantee',
    'reservation.why.price.desc': 'Competitive prices for accommodation by the sea',
    'reservation.why.service': '24/7 service',
    'reservation.why.service.desc': 'We are always at your disposal',
    
    // Gallery
    'gallery.title': 'Lazur Resort Cottages Gallery',
    'gallery.subtitle': 'See our holiday cottages by the sea in Rogowo. Comfortable interiors and beautiful surroundings await you.',
    'gallery.exterior': 'Exterior views',
    'gallery.interior': 'Cottage interiors',
    'gallery.comfort.title': 'Each cottage offers full comfort',
    'gallery.space.title': 'Living space',
    'gallery.space.bedrooms': '2 bedrooms for 8 people',
    'gallery.space.living': 'Living room with sofa bed',
    'gallery.space.kitchen': 'Fully equipped kitchen',
    'gallery.space.bathroom': 'Bathroom with shower',
    'gallery.relax.title': 'Relaxation zone',
    'gallery.relax.terrace': 'Large terrace with furniture',
    'gallery.relax.garden': 'Private garden',
    'gallery.relax.grill': 'BBQ area',
    'gallery.relax.parking': 'Parking at cottage',
    'gallery.amenities.title': 'Amenities',
    'gallery.amenities.wifi': 'WiFi and television',
    'gallery.amenities.linen': 'Bed linen and towels',
    'gallery.amenities.pets': 'Pet space',
    'gallery.amenities.beach': '350m to beach',
    
    // Pricing
    'pricing.title': 'Holiday Cottage Pricing',
    'pricing.subtitle': 'Check our competitive prices for staying in cottages by the sea in Rogowo',
    'pricing.season.spring': 'Spring season',
    'pricing.season.spring.desc': 'Perfect for peaceful spring relaxation',
    'pricing.season.mayday': 'May holidays',
    'pricing.season.mayday.desc': 'Long May weekend',
    'pricing.season.prevacation': 'Pre-vacation season',
    'pricing.season.prevacation.desc': 'Excellent time before summer season',
    'pricing.season.summstart': 'Summer beginning',
    'pricing.season.summstart.desc': 'Start of summer season',
    'pricing.season.high': 'High season',
    'pricing.season.high.desc': 'Best time for family vacation',
    'pricing.season.summend': 'Summer end',
    'pricing.season.summend.desc': 'Quieter end of vacation',
    'pricing.season.autumn': 'Autumn season',
    'pricing.season.autumn.desc': 'Golden Polish autumn by the sea',
    'pricing.cottage.4': 'Cottage for 4 people:',
    'pricing.cottage.56': 'Cottage for 5-6 people:',
    'pricing.cottage.78': 'Cottage for 7-8 people:',
    'pricing.per.night': 'zł/night',
    'pricing.includes.title': 'What is included in the cottage price?',
    'pricing.includes.accommodation': 'Accommodation for up to 4, 6 or 8 people',
    'pricing.includes.bedrooms': '2 bedrooms + living room with sofa bed',
    'pricing.includes.kitchen': 'Fully equipped kitchen',
    'pricing.includes.bathroom': '1 bathroom with shower',
    'pricing.includes.terrace': 'Large terrace with garden furniture',
    'pricing.includes.wifi': 'WiFi and satellite TV',
    'pricing.includes.grill': 'BBQ area',
    'pricing.includes.parking': 'Free parking',
    'pricing.includes.linen': 'Bed linen and towels',
    'pricing.includes.beach': '5 minutes walk to sea',
    'pricing.terms.title': 'Booking conditions',
    'pricing.terms.minimum': 'Minimum booking: 2 nights',
    'pricing.terms.checkin': 'Check-in: from 15:00',
    'pricing.terms.checkout': 'Check-out: until 10:00',
    'pricing.terms.deposit': 'Deposit: 20% of stay value',
    'pricing.terms.pets': 'Pets: allowed for additional fee 15 zł/day',
    'pricing.terms.distance': 'Distance to sea: 350 meters',
    'pricing.terms.parking': 'Parking: free at each cottage',
    'pricing.additional.title': 'Additional information',
    'pricing.additional.desc': 'Cottage for 8 people: 2 bedrooms + living room with fold-out sofas and corner bed',
    'pricing.cta.title': 'Ready for an unforgettable stay?',
    'pricing.cta.subtitle': 'Book your cottage by the sea today and enjoy comfortable vacation in Rogowo',
    'pricing.cta.button': 'Check availability',
    
    // Area
    'area.title': 'Discover the Area',
    'area.subtitle': 'Rogowo is an ideal base for exploring beautiful coastal towns. Discover the charms of nearby towns and regional attractions.',
    'area.mrzezyna.title': 'Cottages for rent Mrzeżyn',
    'area.mrzezyna.desc': 'Peaceful seaside town with beautiful beach and charming fishing port.',
    'area.dzwirzyno.title': 'Cottages for rent Dźwirzyno',
    'area.dzwirzyno.desc': 'Picturesque place between sea and Resko Przymorskie lake.',
    'area.kolobrzeg.title': 'Cottages for rent Kołobrzeg',
    'area.kolobrzeg.desc': 'Famous seaside resort with numerous attractions and monuments.',
    'area.pets.title': 'Accommodation with dog',
    'area.pets.desc': 'Ideal places for dog owners with pet-friendly regulations.',
    'area.bikes.title': 'Bike paths',
    'area.bikes.desc': 'Scenic bike routes along the coast and through forests.',
    'area.why.title': 'Why choose Rogowo?',
    'area.why.location': 'Central Location',
    'area.why.location.desc': 'Ideal location between Kołobrzeg, Mrzeżyn and Dźwirzyno',
    'area.why.beach': 'Beach Proximity',
    'area.why.beach.desc': 'Just a few minutes drive to beautiful Baltic beaches',
    'area.why.nature': 'Peace and Nature',
    'area.why.nature.desc': 'Surrounded by forests and greenery, away from city noise',

    // Common
    'button.book': 'Booking',
    'button.contact': 'Contact',
    'button.more': 'Learn more',
    'button.back': 'Back',
    'button.gallery': 'View gallery',
    'required': '*',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pl');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};